int32 path_source
string path_name        # ROS topic name or path file url
string path_file_location   # path file location
int32 controller          # select a controller
---
# Result
PathTrackingError destination_error
---
# Feedback
PathTrackingError global_path_deviation

float64 prediction_horizon
float64 compute_time

geometry_msgs/Twist control
TwistArray control_list
