name: Build Debian packaging

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_debs:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        package_dir: [kompass, kompass_interfaces]
    name: Build debs
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Create ROS debs for ${{ matrix.package_dir }}
        uses: automatika-robotics/create-ros-debs-action@v1
        working-directory: ${{ matrix.package_dir }}
        with:
          ros-versions-matrix: 'humble jazzy kilted rolling'

      - uses: actions/upload-artifact@v4
        with:
          name: debs-${{ strategy.job-index }}
          path: ./debs/*.deb
