name: Build Debian packaging

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_debs:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    name: Build debs
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Run create-ros-debs-action for kompass package
      - name: Create ROS debs in kompass
        uses: automatika-robotics/create-ros-debs-action@v1
        with:
          ros-versions-matrix: 'humble jazzy kilted rolling'
        working-directory: kompass

      # Run create-ros-debs-action for kompass_interfaces package
      - name: Create ROS debs in kompass_interfaces
        uses: automatika-robotics/create-ros-debs-action@v1
        with:
          ros-versions-matrix: 'humble jazzy kilted rolling'
        working-directory: kompass_interfaces

      - uses: actions/upload-artifact@v4
        with:
          name: debs-${{ strategy.job-index }}
          path: ./debs/*.deb
